config/routes.rb
SecondApp::Application.routes.draw do
  resources :users do
      resources :messages, only: [:create, :show, :destroy, :index]
      resource :options, only: [:update]
      get :private_message
    member do
      get :following, :followers, :feed
    end
  end

  resources :microposts do
    member do
      post :reply
    end
  end
  root  'static_pages#home'
  match '/signup',  to: 'users#new',      via: 'get'
  get   'confirmation/:id' => 'users#end_of_registration', as: :confirm
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  resources :users
  resources :sessions, only: [:new, :create, :destroy, :edit]
  resources :microposts, only: [:create, :destroy, :show]
  resources :relationships, only: [:create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/forgot', to: 'sessions#forgot',        via: 'get'
  match '/remind', to: 'sessions#remind',        via: 'post'
  match '/search', to: 'microposts#search',       via: 'get'
  match '/auth/vkontakte/callback' => 'sessions#vk', via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
has_many :microposts, dependent: :destroy
has_many :relationships, foreign_key: "follower_id", dependent: :destroy
has_many :followed_users, through: :relationships, source: :followed
has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
has_many :followers, through: :reverse_relationships, source: :follower
has_many :messages, inverse_of: :user, dependent: :destroy
has_many :recieve_messages, foreign_key: "reciever_id", class_name: "Message"
has_many :recieve_messages_unread, -> { where :read => false }, foreign_key: "reciever_id", 
            class_name: "Message", inverse_of: :user
has_one :option, dependent: :destroy
before_create :create_remember_token
before_save { self.email = email.downcase }
validates :name,  presence: true, length: { maximum: 50 }
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
						uniqueness: { case_sensitive: false }
has_secure_password
validates :password, length: { minimum: 6 }

def User.new_remember_token
    SecureRandom.urlsafe_base64
end

def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
end

def feed
    Micropost.from_users_followed_by(self)
end

def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
end

def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
end

def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy!
end

def send_private(other_user, cont)
    messages.create!(reciever_id: other_user.id, content: cont)
end


def all_reply
    Micropost.replies(self)
end

def only_mic
  Micropost.microposts_without_reply(self)            
end

private

def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy, :following, :followers, :private_message]
  before_action :correct_user,   only: [:feed, :edit, :update, :all_messages]
  before_action :admin_user, only: [:destroy]
  after_action :send_confirm, only: [:create]

  def new
  redirect_to root_url if current_user
  @user = User.new
  end

  def feed
    @user = User.find_by(id: params[:id])
    @replies = @user.all_reply(order: "updated_at DESC", limit: 5)
    @relationships = @user.reverse_relationships
    @messages = @user.recieve_messages
    @followers = @user.followers 
  end

  def private_message
    @user = User.find(params[:user_id])
    @message = current_user.messages.build
  end

  def index
  @users = User.paginate(page: params[:page])
  
  end

  def show
  @user = User.find(params[:id])
  @microposts = @user.only_mic.paginate(page: params[:page])
  end

  def edit
  end 

  def user_params_updates
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def update
    if @user.update_attributes(user_params)
    flash[:success] = "Profile updated"
    redirect_to @user
    else
    render 'edit'
    end
  end

  def create
    redirect_to root_url if current_user
    @user = User.new(user_params)  
    if @user.save
    @user.create_option
    @user.toggle!(:active)
    flash[:success] = "На ваш e-mail отправлено письмо о подтверждении регистрации" 
    redirect_to root_url
    #sign_in @user
    #flash[:success] = "Welcome to the Sample App!"
    #redirect_to @user
    else
      render 'new'
    end
  end

  def end_of_registration
      user = User.find_by(:remember_token => User.encrypt(params[:id]))
      if user && user.created_at > 5.day.ago
      user.toggle!(:active)
      sign_in user
      flash[:success] = "Пользователь активирован"
      redirect_to user
    else
      user.destroy if user
      flash[:error] = "Такой пользователь не существует"
      redirect_to signin_path
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

    def send_confirm
    remember_token = User.new_remember_token
    @user.update_attribute(:remember_token, User.encrypt(remember_token))
    UserMailer.send_confirm(@user, remember_token).deliver
    end

end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id), remote: true) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
  <%= button_to "Message", user_private_message_path(@user.id), method: "get" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(followed_id: @user),
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/_users.html.erb
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>
<%= form_tag user_options_path(@user), method: "patch" do %>
  <div class="set">
  	<ul>
  		<li class="set-f">Настройки:</li>
  		<div class="set-drop">
        <% notice = false || current_user.option.email_notice.class if current_user.option != nil %>
  			<li><%=check_box_tag(:email_notice, "1", notice) %><%= label_tag(:email_notice, "Включить почтовые уведомления о новых читателях") %></li>
  			<li><%=check_box_tag(:adv) %><%= label_tag(:adv, "Дополнительные настройки(в разработке)") %></li>
  			<li><%= submit_tag "Обновить", class: "bottom_reply" %></li>
  		</div>
  	</ul>
  </div>
  <% end %>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= render 'users', f: f %>
    <%=f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <%= gravatar_for @user %>
    <%end%>

    <a href="http://gravatar.com/emails" target="_blank">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate(previous_label: "Предыдущая", next_label: "Следущая") %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= render 'users', f: f %>
    <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/private_message.html.erb
<section>
<div class="grav_user">
<%= link_to gravatar_for(current_user, size: 56), current_user %>
<h1 class="gravatar"><%= current_user.name %></h1>
</div>
</section>
<section>
<%= render 'shared/error_messages', object: @message %>
<%= form_for ([current_user, current_user.messages.build(reciever_id: @user.id)]) do |message| %>
<%= message.hidden_field :reciever_id %>
<%= message.text_area :content, class: "text_field " %>
<%= message.submit "Submit", class: "bottom_reply"  %>
<% end %>
</section>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <section>
      <%= render 'shared/stats' %>
    </section>
  </aside>
</div>
 <div class="span8">
  <%= render 'follow_form' if signed_in? %>
    <% if @user.only_mic.any? %>
      <h3>Microposts (<%= @user.only_mic.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="span4">
    <section>
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section>
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="span8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>