config/routes.rb
SecondApp::Application.routes.draw do
  resources :users do
      resources :messages, only: [:create, :show, :destroy, :index]
      resource :options, only: [:update]
      get :private_message
    member do
      get :following, :followers, :feed
    end
  end

  resources :microposts do
    member do
      post :reply
    end
  end
  root  'static_pages#home'
  match '/signup',  to: 'users#new',      via: 'get'
  get   'confirmation/:id' => 'users#end_of_registration', as: :confirm
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  resources :users
  resources :sessions, only: [:new, :create, :destroy, :edit]
  resources :microposts, only: [:create, :destroy, :show]
  resources :relationships, only: [:create, :destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/forgot', to: 'sessions#forgot',        via: 'get'
  match '/remind', to: 'sessions#remind',        via: 'post'
  match '/search', to: 'microposts#search',       via: 'get'
  match '/auth/vkontakte/callback' => 'sessions#vk', via: 'get'

end

app/views/shared/_delete_link_micropost.html.erb
<% if current_user?(object.user) %>
    <%= link_to "delete", object, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: object.content %>
  <% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
<%= will_paginate @feed_items %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content"><%= feed_item.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
  <%= render 'shared/delete_link_micropost', object: feed_item %>
</li>

app/views/shared/_home.html.erb
<div class="center hero-unit">
    <h1>Welcome to the Sample App</h1>

    <h2>
      This is the home page for the
      <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
      sample application.
    </h2>
    <%= link_to "Sign up now!", signup_path,
                                class: "btn btn-large btn-primary" %>
    <%= link_to image_tag("vk.jpg", alt:"Vk", size: "50x50"), "/auth/vkontakte" %>                            
  </div>

  <%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/shared/_home_signed_in.html.erb
<div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/stats' %>
      </section>
      <section>
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="span8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_rep.html.erb
<% if @micropost.id.to_s == rep.including_replies %>
<li class="comment">
	<%= gravatar_for rep.user, size: 25 %>
	<span class="com_u_name"><%=rep.user.name%></span><span class="gav">@
	</span><%= rep.content %>
	<span class="timestamp">Posted <%= time_ago_in_words(rep.created_at)%> ago</span>
<li>
<% end %>

app/views/shared/_reply_form.html.erb
<%= form_for(current_user.microposts.build(in_reply_to: @user.id, 
				including_replies: @micropost.id), url: {action: 'reply'}) do |f| %> 
<%= f.hidden_field :in_reply_to %>
<%= f.hidden_field :including_replies %>
<%= f.text_area :content, placeholder: "Compose new reply...", class: "form_reply_form"%>
<%= f.submit "Reply", class: "bottom_reply"  %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
  <% if current_user?(@user) %>
  <a href="<%= user_messages_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.recieve_messages_unread.count %>
    </strong>
    messages
  </a>
  <% end %>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 52), current_user %>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>